global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["ip:6000"]
        labels:
          instance: "main-server"
      - targets: ["ip:6000"]
        labels:
          instance: "vps-2"
      - targets: ["ip:6000"]
        labels:
          instance: "vps-3"
    metrics_path: "/api/v1/metrics"
